name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          echo "Customize this step by language (Node/Python/Go/Java)"
      - name: Run Make Tests
        run: |
          if [ -f Makefile ]; then
            make test
          else
            echo "No Makefile found — add language-specific tests in the workflow"
